### ISSUE TITLE
Usage instructions?

### ISSUE THREAD

**Issue by guidedways** [nickynick/ArrayDiff#2]
This looks like a great repository! We've done something similar in the past but not as generic. 

Would be great to have some instructions on the main page to learn how to use this. Thanks.

**Comment by nickynick** [comment]
Hey! For a long time this has been a semi-private project for my internal usage, sorry I didn't respond timely :) Now I've finally added a quick intro and published the project on CocoaPods, feel free to check it out. More docs are coming soon (hopefully).
